### ISSUE TITLE
build lprey/main.go

### ISSUE THREAD

**Issue by 1amfine2333** [Maka8ka/NGLite#2]
lprey/main.go:122:2: syntax error: non-declaration statement outside function body
![image](https://user-images.githubusercontent.com/24676292/126106832-695d41ee-2b95-4687-b4f4-9cbcb8463e6a.png)

**Comment by badboycxcc** [comment]
![image](https://user-images.githubusercontent.com/72059221/128034281-1ebd55ee-c73c-4141-abda-da1b0a2c63ea.png)
142行括号没有闭合，122行应该是在函数内进行定义，具体可以参见43行。感觉缺少一个函数。

**Comment by NuclearEris** [comment]
确实缺少了函数，源码并没有完全开源

**Comment by Maka8ka** [comment]
func Sender(srcid string, dst string, acc *nkn.Account, msg interface{}) (string, error) {
